# ── Certificates Module Outputs ──────────────────────────────────────────────

output "certificate_pem" {
  description = "PEM-encoded X.509 certificate generated by the certs module"
  value       = module.certs.ca_certificate_pem
}

output "private_key_pem" {
  description = "PEM-encoded private key generated by the certs module"
  value       = module.certs.ca_private_key_pem
  sensitive   = true
}

# ── Genesys Cloud Module Outputs ──────────────────────────────────────────────

output "genesys_oauth_client_id" {
  description = "Client ID for the Genesys Cloud OAuth client"
  value       = module.genesys.genesyscloud_oauth_client_id
   sensitive = true
}

output "genesys_oauth_client_secret" {
  description = "Client Secret for the Genesys Cloud OAuth client"
  value       = module.genesys.genesyscloud_oauth_client_secret
  sensitive   = true
}

# ── ServiceNow Module Outputs ────────────────────────────────────────────────

output "servicenow_certificate_sys_id" {
  description = "sys_id of the uploaded X.509 certificate in ServiceNow"
  value       = module.servicenow.certificate_sys_id
}

output "servicenow_oauth_entity_id" {
  description = "sys_id of the OAuth JWT API endpoint record in ServiceNow"
  value       = module.servicenow.oauth_entity_sys_id
}

output "servicenow_integration_user_sys_id" {
  description = "sys_id of the integration user created in ServiceNow"
  value       = module.servicenow.integration_user_sys_id
}

output "servicenow_jwt_verifier_map_sys_id" {
  description = "Sys ID of the JWT Verifier Map entry in ServiceNow"
  value       = module.servicenow.jwt_verifier_map_sys_id
}

